name: shyari_by_piyush
description: Shayari Hub All Shayari by Piyush
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.0
  share_plus: ^10.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
