name: shyari_by_piyush
description: Shayari app by Piyush
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.0

flutter:
  uses-material-design: true
